apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: authelia-ingress
  namespace: authelia
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
spec:
  # tls:
  # - secretName: authelia-ingress-tls
  #   hosts:
  #   - auth.dummy-service.com

  rules:
    - host: ec2-3-250-220-107.eu-west-1.compute.amazonaws.com 
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: authelia-service
              port:
                number: 80