apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  labels:
    app: hello-world
spec:
  selector:
    matchLabels:
      app: hello-world
  replicas: 2
  template:
    metadata:
      labels:
        app: hello-world
    spec:  # Fix indentation here
      containers:
        - name: hello-world
          image: bhargavshah86/kube-test:v0.1
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: 256Mi
