apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: default

spec:
  selector:
    app: nginx  # Match labels in the pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80